baseurl = "https://www.stuartellis.name"
languageCode = "en-us"
title = "Field Notes"
theme = "liquorice"
disqusShortname = "fieldnotes-1"

[params]
author = "Stuart Ellis"
copyright = "Contents © 2019 Stuart Ellis"

[[menu.main]]
name = "Articles"
pre = "<i class='fa fa-heart'></i>"
weight = -100
identifier = "articles"
url = "/articles/"

[[menu.main]]
name = "Projects on GitLab"
pre = "<i class='fa fa-heart'></i>"
weight = -90
identifier = "gitlab"
url = "https://gitlab.com/users/stuart-ellis/projects"

[[menu.main]]
name = "Privacy"
pre = "<i class='fa fa-heart'></i>"
weight = -80
identifier = "privacy"
url = "/privacy/policy/"

[[menu.main]]
name = "Contact Me"
pre = "<i class='fa fa-heart'></i>"
weight = -70
identifier = "contact"
url = "/contact/me/"
