baseurl = "http://www.stuartellis.name"
languageCode = "en-us"
title = "Field Notes"
theme = "liquorice"
disqusShortname = "fieldnotes-1"

[params]
author = "Stuart Ellis"
copyright = "Contents © 2018 Stuart Ellis"
googleAnalytics = "UA-23721911-2"

[[menu.main]]
name = "Articles"
pre = "<i class='fa fa-heart'></i>"
weight = -100
identifier = "articles"
url = "/articles/"

[[menu.main]]
name = "Projects on GitHub"
pre = "<i class='fa fa-heart'></i>"
weight = -90
identifier = "github"
url = "https://github.com/stuartellis"

[[menu.main]]
name = "Contact Me"
pre = "<i class='fa fa-heart'></i>"
weight = -80
identifier = "contact"
url = "/contact/me/"
