baseurl = "http://www.stuartellis.name"
languageCode = "en-us"
title = "Field Notes"
theme = "liquorice"
disqusShortname = "fieldnotes-1"

[params]
author = "Stuart Ellis"
copyright = "Contents © 2017 Stuart Ellis"
googleAnalytics = "UA-23721911-2"

[[menu.main]]
name = "Categories"
pre = "<i class='fa fa-heart'></i>"
weight = -110
identifier = "categories"
url = "/categories/"

[[menu.main]]
name = "Projects on GitHub"
pre = "<i class='fa fa-heart'></i>"
weight = -100
identifier = "github"
url = "https://github.com/stuartellis"

[[menu.main]]
name = "Contact Me"
pre = "<i class='fa fa-heart'></i>"
weight = -90
identifier = "contact"
url = "/contact/"
