---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Static website'

Parameters:

  SiteName:
    Description: 'The DNS name for the site, e.g. www'
    Type: 'String'
    Default: 'www'

  DomainName:
    Description: 'The DNS domain for the site, e.g. example.com'
    Type: 'String'

  AcmCertificateArn:
    Description: 'The ARN for the TLS certificate used by CloudFront'
    Type: 'String'

  DefaultRootObject:
    Description: 'The name of the index document for the website.'
    Type: 'String'
    Default: 'index.html'

Resources:

######## S3 Bucket for content

  S3ContentBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${SiteName}.${DomainName}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended

  S3ContentBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3ContentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AddGetObject'
            Action: 's3:GetObject'
            Effect: Allow
            Resource: !Join
                        - ''
                        - - !GetAtt S3ContentBucket.Arn
                          - '/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId   

######## CloudFront distribution

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Join
                   - '.'
                   - - !Ref 'SiteName'
                     - !Ref 'DomainName'

  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Join
              - '.'
              - - !Ref 'SiteName'
                - !Ref 'DomainName'
        Comment: !Join
                   - '.'
                   - - !Ref 'SiteName'
                     - !Ref 'DomainName'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400
          MinTTL: 60
          TargetOriginId: s3contentbucket
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: !Ref 'DefaultRootObject'
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt 'S3ContentBucket.DomainName'
            Id: s3contentbucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}' 
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref 'AcmCertificateArn'
          MinimumProtocolVersion: 'TLSv1.2_2018'
          SslSupportMethod: 'sni-only'
  Route53RecordSet:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      RecordSets:
        - Name: !Sub '${SiteName}.${DomainName}.'
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # Generic ID for any CloudFront
            DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
